### ISSUE TITLE
handle_to_many_relation error

### ISSUE THREAD

**Issue by cilim** [visualitypl/jsonapi_parameters#13]
Hello 👋 

I tried using `jsonapi_parameters` but I'm getting an error in the `handle_to_many_relation` method.

This is my request:
**POST** *http://localhost:3000/api/v1/movies*
*payload*:
```
{"data"=>
  {"type"=>"movies",
   "attributes"=>
    {"title"=>"The Terminator",
     "released_at"=>"1984-10-26",
     "runtime"=>107,
     "content_rating"=>"restricted",
     "storyline"=>
      "A seemingly indestructible android is sent from 2029 to 1984 to assassinate a waitress, whose unborn son will lead humanity in a war against the machines, while a soldier from that war is sent to protect her at all costs.",
     "budget"=>6400000},
   "relationships"=>{"genres"=>{"data"=>[{"id"=>74, "type"=>"genres"}]}, "director"=>{"data"=>{"id"=>682, "type"=>"directors"}}}}}
```
*error*:
```
 NoMethodError:
       undefined method `merge' for nil:NilClass
```

It breaks when trying to execute this `included_object[:attributes].merge(id: related_id)` because the `included_object` is nil.
The `related_id` and `related_type` are properly set and the record exists in the database and the `@jsonapi_unsafe_hash` is properly set.

The issue I believe is in the convention you used for including relationships. As specified in the [JSON:API documentation](https://jsonapi.org/format/#fetching-includes), `include` is the query parameter used for relationship inclusion and you used `included`:
```
def jsonapi_included
  @jsonapi_included ||= @jsonapi_unsafe_hash[:included] || []
end
```
Also, you assume that the request will look like this:

**POST** *http://localhost:3000/api/v1/movies?include=genres,director*

A client doesn't need to include the relationships if he's creating them necessarily.

After changing the query parameter to `included`, it broke in the `find_included_object` method, because it doesn't support including relationships by separating with a comma like JSON:API specifies is possible.

I'm using Ruby `2.5.1` on Rails `5.2.1`.

Thanks!

**Comment by Marahin** [comment]
Hi!

Lets tackle issues that you mentioned in the end, about the `included` vs `include` keyword and its functionality. 
I may have misunderstood (if so, sorry for that, and please correct the track of my thoughts), but you're speaking of the `include` functionality that JSON:API provides for _fetching_ the resources, not _creating_ or _updating_ them. 

jsonapi_parameters gem is purely for *deserialization*, so `include` keyword and its functionality that allows the client to specify what kind of resources would he like to receive should not be cared about in this library. 

## `included` vs `include`

I think you have missed the section about [Compound documents](https://jsonapi.org/format/#document-compound-documents). Basically, the way we understood it, is that along with creating a resource that has some kind of relationships, we may also want to create these related objects. In this case, as specified in the documentation, the client should pass `included` top-level key that contains attributes for each of the resources you can find in the `relationships` tree (as there the only things you have is the `type` and `id`).

 ## `undefined method `merge' for nil:NilClass`

Even if `included` vs `include` section was misunderstood by me, the idea we had with relationships - if I recall correctly - was to have the following functionality:

* if relationships is passed, check for `included` tree
* if the `included` tree contains attributes, pass them along with the relationship data,
* if not, then just pass the ids to those related objects

It seems that this flow is failing us, as in your example you provided relationships but not included data for them - so it should not fail, but just yield something like `genres_ids: [74], director_id: 682`. I need to dig into that. 

Please let me know your thoughts on this!

**Comment by Marahin** [comment]
I have opened a PR that should resolve the latter part. jsonapi_parameters should no longer fail with the request example you provided, and the specific parameters have been added to the test suite.

**Comment by cilim** [comment]
Hi @Marahin 👋 

Thanks for jumping on this issue so quickly!

> Lets tackle issues that you mentioned in the end, about the included vs include keyword and its functionality.
I may have misunderstood (if so, sorry for that, and please correct the track of my thoughts), but you're speaking of the include functionality that JSON:API provides for fetching the resources, not creating or updating them.

Let's quickly mark this part as resolved. I assumed that part wrong when I was debugging the code. :)

> It seems that this flow is failing us

Great job! That's exactly what I was looking for. However, I checked out your branch and bundle installed everything once more to try it out:

```
def movie_params
  params.from_jsonapi.require(:movie).permit(
    :title, :released_at, :runtime, :content_rating,
    :storyline, :budget, director: [:id], genres: [:id]
  )
end
```

When I pry the params before sending them to my form object, I get this:
```
<ActionController::Parameters {"title"=>"The Terminator", "released_at"=>"1984-10-26", "runtime"=>107, "content_rating"=>"restricted", "storyline"=>"A seemingly indestructible android is sent from 2029 to 1984 to assassinate a waitress, whose unborn son will lead humanity in a war against the machines, while a soldier from that war is sent to protect her at all costs.", "budget"=>6400000} permitted: true>
```

The relationship attributes are ignored.

I also tried setting up the parameters like this:
```
def movie_params
  params.from_jsonapi.require(:movie).permit(
    :title, :released_at, :runtime, :content_rating,
    :storyline, :budget, :director_id, :genre_ids
  )
end
```

This time the `:director_id` is present, but the `:genre_ids` aren't.

**Comment by Marahin** [comment]
>Let's quickly mark this part as resolved. 
👍 

>When I pry the params before sending them to my form object, I get this:

So first things first - I have added your request parameters as an example to the test suite ([source](https://github.com/visualitypl/jsonapi_parameters/blob/85ee690a4d41d1113a369adc56f4f727bff55808/spec/support/inputs_outputs_pairs.rb#L182)). The tests are passing, so the expected outcome is what is actually translated. [Here](https://github.com/visualitypl/jsonapi_parameters/blob/85ee690a4d41d1113a369adc56f4f727bff55808/spec/support/inputs_outputs_pairs.rb#L210-L220) you can see what is the result of the translation (raw parameters, without `.require`).

So the parameters are translated. 

In order to use these in your controller, you would have to require them in this way: 

```
params.from_jsonapi.require(:movie).permit(:director_id, :genres_ids)
```

So instead of `director: [:id]` which essentially is looking for an array of ids (`director: [1, 2, 3]`) you just use the column name, as one-to-one relationship works: https://guides.rubyonrails.org/association_basics.html#the-belongs-to-association

Instead of `genres: [:id]` you should pass `:genres_ids`  or `:genre_ids` as the hash structure should only be provided if `genres` was an array of hashes (e.g. `genres: [ { id: 1, name: ‘test’ }, … ]`). However, since you are not passing any genre data into the `included` tree, there are no other parameters other than ids, hence its sufficient to just pass an array of these ids - by specifying the parameter as `:genres_ids`. Rails should handle it.

What is interesting and makes me uncertain about the `genres_ids` vs `genre_ids` is how naturally you expected it to be visible under the singular name, and I have to double check in the Rails examples on how should it be really named, because I thought its the plural version (`genres_ids`).

**Comment by Marahin** [comment]
OK. After quick checking, the naming you tried to use seems to be the correct one! I will push a quick fix for my branch and then you should be set.

**Comment by Marahin** [comment]
@cilim please let me know if https://github.com/visualitypl/jsonapi_parameters/pull/14 branch works for you, and if so, let's get this published! :)

**Comment by cilim** [comment]
@Marahin you said it all 🙂 

And I confirm that branch #14 works perfectly. Finally, the param are set like this:

```
def movie_params
  params.from_jsonapi.require(:movie).permit(
    :title, :released_at, :runtime, :content_rating,
    :storyline, :budget, :director_id, genre_ids: []
  )
end
```

Thanks for jumping on this issue and solving it in such a short time 👏 
Let me know when you release a new version!

**Comment by Marahin** [comment]
@cilim the branch has been merged and I'm currently pushing out the new version. Thanks for reaching out!
