### ISSUE TITLE
Nullifying relationship doesn't adhere to spec

### ISSUE THREAD

**Issue by batshoes** [visualitypl/jsonapi_parameters#18]
Hey mate! 
First up, love what you're doing, however I've run into an issue where when deleting or nullifying a relationship the gem does not adhere to the spec. 

From the [JSON:API  spec](https://jsonapi.org/format/#crud-updating-to-one-relationships)
![image](https://user-images.githubusercontent.com/12520948/64745077-c7078b00-d549-11e9-8754-65454adc875e.png)

However the same request results in a failure 
```JSON
PATCH
{
  "data": {
    "type": "account",
    "id": "1394dacc-c682-4b80-81cc-8ef4aba72742",
    "attributes": {
      "name": "foo",
      "type": "bar",
    },
    "relationships": { "owner": { "data": null } }
  }
}
```
```
NotImplementedError: relationship member must either be an Array or a Hash
from /Users/.../.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/jsonapi_parameters-0.3.0/lib/jsonapi_parameters/translator.rb:45:in `block (2 levels) in jsonapi_main_body'
```

This can be rectified in the current version of the gem by setting 

`"relationships": { "owner": { "data": {} } }` 

However this does not adhere to the spec as above. 
I believe the following lines { 39:46 } of the translator are to blame and can be updated to include a nil value option. Assuming that if a nil value has been explicitly passed then the PATCH request should be treated as a removal of relationship.

Love to hear your thoughts mate. Cheers.

**Comment by Marahin** [comment]
Hey and thanks for reaching out!

From the information you provided it seems that you are correct, and the behaviour of the library does not represent the specification correctly. We will do our best to check the details and implement the `nil` handling in the nearest future. 

Feel invited to provide a pull request with the solution though!

Thanks!

**Comment by Marahin** [comment]
Since we merged, I'll close this issue now.
