### ISSUE TITLE
Translate the data type as well

### ISSUE THREAD

**Issue by attilahorvath** [visualitypl/jsonapi_parameters#30]
Currently the data type is not being translated from camel case to underscores even with the `ensure_underscore_translation` setting being set to `true`. E.g. if I receive:

```json
{"data": {"type": "myTestModel", "id": 123, "attributes": {}}}
```

Then I would expect the following to work:

```ruby
params.from_jsonapi.require(:my_test_model)
```

I think it's just the case of calling `#underscore` in `#jsonapi_main_key` as well and I'd be happy to submit a PR for that but I wanted to hear your input first as this would be a breaking change - any project that relies on the data type being kept in camel case would need to be updated to snake case. Or this could be a separate config option maybe.

Let me know what you think.

**Comment by Marahin** [comment]
Hello and thanks for reaching out!

Sorry it took us this long to respond, we are working on improving our open source culture at Visuality to provide better maintenance to our projects.

This seems like a valid issue. I'll be checking your PR as soon as possible!
