### ISSUE TITLE
How to permit dashed parameters

### ISSUE THREAD

**Issue by koushikmohan1996** [visualitypl/jsonapi_parameters#40]
I have some dashed parameters and I am trying to permit it with below options and it does not work.
```rb
params.from_jsonapi(:dashed).require(:project).permit(:jira_settings)
```
and

```rb
params.from_jsonapi(:dashed).require(:project).permit('jira-settings')
```

Finally, I had to do this
```rb
params_data = params.from_jsonapi(:dashed).require(:project)
 jira_settings = params_data[:jira_settings].permit!
```

So whats the correct way to do this?

**Comment by Marahin** [comment]
Hello,

thanks for reaching out and providing detailed steps on how to reproduce the issue. We'll investigate and get back to you shortly!

**Comment by Marahin** [comment]
@koushikmohan1996 Could you provide us some parameters so we can reproduce the issue? 
Technically, we have our own set of tests:

* https://github.com/visualitypl/jsonapi_parameters/blob/master/spec/lib/jsonapi_parameters/translator_spec.rb#L67
* https://github.com/visualitypl/jsonapi_parameters/blob/master/spec/support/inputs_outputs_pairs.rb

So we should be covered here, but perhaps you are facing some edge case or malfunctioning part of the library.

**Comment by koushikmohan1996** [comment]
@Marahin I think testcase is correct and it even worked if I do something like this
```rb
params.from_jsonapi(:dashed).require(:project)[:jira_settings]
```

I guess the issue is with `permit` API may be.

**Comment by koushikmohan1996** [comment]
@Marahin A test for dashed controller may reveal the issue.

Like this https://github.com/visualitypl/jsonapi_parameters/blob/master/spec/integration/authors_camel_controller_spec.rb

**Comment by Marahin** [comment]
@koushikmohan1996 sorry, but I'm unable to reproduce the issue. I have brought some extra steps to make sure tests are covering dasherized parameters, including your suggestion to create a dasherized controller, and it all worked. I even enabled the debugger and checked how does it look in our input/output pair expectations, and:


```
0> input 
=> {:data=>{:type=>"MessageBoardThreads", :attributes=>{:"thread-title"=>"Introductory Thread"}}}

0> translated_input = described_class.new.jsonapify(input, naming_convention: :dashed)
=> {:message_board_thread=>{:thread_title=>"Introductory Thread"}}
```


We have `data.attributes.thread-title`, and in the output, we have `message_board_thread.thread_title`, so it seems everything is good. 
I went on and even made sure that the `#permit` method call will work (although that doesn't seem like its necessary, as we have tests for that too):


```
0> ActionController::Parameters.new(input).from_jsonapi(:dashed).require(:message_board_thread).permit(:thread_title)
=> <ActionController::Parameters {"thread_title"=>"Introductory Thread"} permitted: true>
```

And it also works.
Please provide us some steps to reproduce this issue along with a set of parameters that is not working for you.

**Comment by koushikmohan1996** [comment]
@Marahin Thanks for the effort. I will check and let you know

**Comment by koushikmohan1996** [comment]
@Marahin I found out what is wrong with my setup, I have nested params so it also need to be added in permit method
```rb
params.from_jsonapi(:dashed).require(:project).permit(:jira_settings, {:jira_settings => [:username]})
```
I am sorry, I am new to ruby. Really appreciate your effort. Thanks
