### ISSUE TITLE
Parameters not parsed

### ISSUE THREAD

**Issue by shaicoleman** [visualitypl/jsonapi_parameters#7]
Rails does not parse the JSON params unless the MIME type is registered.
This should either be documented in the README or automatically register the MIME type
```
Mime::Type.register 'application/vnd.api+json', :json
```

**Comment by Marahin** [comment]
This gem's sole purpose is to allow to easily consume JSON:API compliant input in the Rails application. Because of that I think it makes sense to make it register the mime type for the user. 
Thank you for this input.

**Comment by Marahin** [comment]
This issue should be resolved now.
