### ISSUE TITLE
Key transforms (e.g. camelCase to snake_case)

### ISSUE THREAD

**Issue by shaicoleman** [visualitypl/jsonapi_parameters#8]
JSON API 1.1 recommends camelCase of keys.
https://jsonapi.org/recommendations/#naming

The fast_jsonapi allows `set_key_transform` with the following options: `:camel` / `:camel_lower` / `:dash` / `:underscore`, it would be nice if it would have an equivalent feature when parsing parameters.

As a workaround, I currently add `.to_h.deep_transform_keys(&:underscore)` every time I parse the parameters

**Comment by Marahin** [comment]
That's a great suggestion! I'll try to work on that today.
